physics:
  initial_state: [0.5, 7.0, 30, 0.0]  # [x, y, theta (degrees), gamma (degrees)]
  target: [0.0, 0.0]
  turning_radius: 1.5
  dt: 0.05

controller:
  constant_vx: -0.1
  K_dist: 48.15           # Weight for the distance cost
  K_turn: 7.97             # Weight for the turning cost
  K_hitch: 17.93          # Weight for the hitch angle cost
  horizon: 10
  lookahead_distance: 0.35

cart_dimensions:
  width: 0.7
  length: 0.5     
  gripper_length: 0.45      # Distance from the robot's center to the gripper
  gripper_angle_limit: 37   # Maximum gripper angle (in degrees)
  fixed_wheel_dist: 0.25    # Distance of grabbing bar to fixed wheels
